apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: alert-service
    {{- include "telemetry-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.alert.replicas }}
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: alert-service
          image: {{ include "telemetry-platform.image" (dict "registry" .Values.global.imageRegistry "name" "telemetry/alert-service" "tag" .Values.global.imageTag) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: telemetry-config
                  key: KAFKA_BROKERS
          ports:
            - containerPort: 8081
          resources:
            {{- toYaml .Values.alert.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
